version: '3'
services:
  sa-webapp:
    network_mode: bridge
    image: tanaphonble/sentiment-analysis-web-app
    ports:
      - '8080:8080'
    environment:
      - SA_LOGIC_API_URL=http://172.17.0.3:5000
